spring:
  profiles:
    active: dev
  application:
    name: citizen-service

  datasource:
    url: jdbc:postgresql://localhost:5433/citizen_registry
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false # recommended: false for production

logging:
  level:
    org.hibernate.SQL: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.query.sqm.ast: TRACE
    org.hibernate.orm.sql.ast: TRACE
    org.hibernate.orm.sql.exec: TRACE
